<div class="d-flex justify-content-center">
    <div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
        <?php
        if ($success === true) {
            echo "Thanks for registering!";
        } else {
            ?>
            <h3>Sorry, the following problems were generated:</h3>
            <ul>
			<?php
            foreach ($registerErrors as $message){
                echo "<li>".$message."</li>";
            }
            ?>
            </ul>
            <?php
        }
        ?>
    </div>
    <br>
</div>
<div class="d-flex justify-content-center">
    <?php echo $this->tag->linkTo(['signup', 'Go back', 'class' => 'btn btn-primary']); ?>
</div>