
<div class="d-flex justify-content-center">
    <?php echo $this->tag->form("signin/login"); ?>
    	<h2>Sign in using this form</h2>
        <div class="form-group input-group-sm">
          <label for="email">Email</label>
          <?php echo $this->tag->textField(["email", "class" => "form-control"]); ?>
        </div>
        <div class="form-group input-group-sm">
          <label for="password">Password</label>
          <?php echo $this->tag->passwordField(["password", "class" => "form-control"]); ?>
        </div>
        <?php
        echo $this->tag->submitButton(["Sign in", "class" => 'btn btn-primary']);
        echo $this->tag->linkTo(["signup", "Sign Up", "class" => 'btn btn-link']);
        ?>
    <?php echo $this->tag->endForm(); ?>
</div>